### ISSUE TITLE
error in running autodock.py

### ISSUE THREAD

**Issue by luongphekidz07** [sarisabban/Notes#3]
Dear Expert,

I am following your instructions to run autodock.py. However, I met the message as below:

python3 /home/leo/Desktop/autodock.py -r /home/leo/Desktop/R.pdb

Traceback (most recent call last):
  File "/home/leo/Desktop/autodock.py", line 65, in <module>
    import pymol
ModuleNotFoundError: No module named 'pymol'

What should I do solve the problem? I installed pymol with sudo apt install pymol

When you have time, could you help me?

Thank you very much for your help,

Kind regards,
Le Phuong.

**Comment by sarisabban** [comment]
This happens when you install a pymol version that runs on python 2. please make sure that you install a version of pymol that works with python 3. if the version in apt does not run on python 3 either install a newer distro or install pymol from the installer in their website.

**Comment by luongphekidz07** [comment]
Dear Expert,
Thank you very much for your advice. I solved the problem by installing from the pymol homepage instead of apt install,
Kind regards,
Le Phuong.
